config/routes.rb
Rails.application.routes.draw do
  root 'remote_control#index'
  
  resources :remote_control, :only => [:index] do
    collection do
      post :take_screenshot
      post :trigger_click
      post :trigger_button
      post :launch_app
      post :watch_channel
      get :channel_guide
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/remote_control_controller.rb
class RemoteControlController < ApplicationController
  before_filter :set_session_ip
  before_filter :perform_with_handler, :except => [:index, :channel_guide]

  def index
  end

  def take_screenshot
    Dir.glob("#{Rails.root.join('public')}/screenshot*.png"){|path| File.delete(path) }
    @handler.take_screenshot
    render :json => @handler.timestamp
  end

  def trigger_click
    @handler.click_screen(params[:click_x], params[:click_y])
    render :nothing => true
  end

  def trigger_button
    @handler.send_button_click(params[:button])
    render :nothing => true
  end

  def launch_app
    @handler.launch_app(params[:app_name])
    render :nothing => true
  end

  def watch_channel
    if params[:watching] == '1'
      @handler.change_channel(params[:channel])
    else
      @handler.watch_channel(params[:channel])
    end
    render :nothing => true
  end

  def channel_guide
    @guide_html = TvGuideExtractor.get_html
  end

  private

  def set_session_ip
    session[:device_ip] = params[:ip_address] if params[:ip_address].present?
  end

  def perform_with_handler
    @handler = AdbHandler.new(params[:ip_address])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/remote_control_helper.rb
module RemoteControlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenCvAdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/remote_control/channel_guide.html.erb
<div>
  <div>
    <%= label_tag 'ip_address', 'Device IP Address' %><br/>
    <%= text_field_tag 'ip_address', session[:device_ip] %>
  </div>
  <div>
    <%= check_box_tag 'watching' %><%= label_tag 'Already Watching?' %>
  </div>
</div>

<%= @guide_html.html_safe %>

<script>
  $('.listings-channel-row').on('click', function(ev, el){
    ev.preventDefault();
    channel = $(this).data('channel-name');
    $.ajax('/remote_control/watch_channel', {
      method: 'POST',
      dataType: 'script',
      data: {ip_address: $('#ip_address').val(), channel: channel, watching: $('#watching:checked').length}
    });
    return false;
  });
  $('[style^="width"]').each(function(){ $(this).css({width: $(this).width() - 1 }) });
  $('.listings-ad-row, .listings-channel-franchise-bar, .listings-channel-row-franchise').remove();
</script>

app/views/remote_control/index.html.erb
<div>
  <div>
    <%= label_tag 'ip_address', 'Device IP Address' %><br/>
    <%= text_field_tag 'ip_address', session[:device_ip] %>
  </div>
  
  <%= link_to 'Take Screenshot', 'javascript:void(0);', :id => 'take_screenshot' %><br/>
  
  <div>
    <%= link_to 'Trigger Click', 'javascript:void(0);', :id => 'trigger_click' %>
    <%= text_field_tag 'click_x' %><%= text_field_tag 'click_y' %>
  </div>
  <div>
    <%= link_to 'Trigger Button', 'javascript:void(0);', :id => 'trigger_button' %>
    <%= select_tag 'button', options_for_select(AdbHandler.button_codes.keys) %>
  </div>
  <div>
    <%= link_to 'Launch App', 'javascript:void(0);', :id => 'launch_app' %>
    <%= select_tag 'app_name', options_for_select(AdbHandler.app_list.keys) %>
  </div>
  <div>
    <%= link_to 'Watch Channel', 'javascript:void(0);', :id => 'watch_channel' %>
    <%= select_tag 'channel', options_for_select(AdbHandler.change_channel_counts.keys.map(&:titleize).map(&:upcase)) %>
    <%= check_box_tag 'watching' %><%= label_tag 'Already Watching?' %>
  </div>
  <div>
    <%= link_to 'Channel Guide', channel_guide_remote_control_index_path %>
  </div>
</div>

<div id="screenshot_container">
</div>


<script>
  $('#take_screenshot').on('click', function(){
    $.ajax('/remote_control/take_screenshot', {
      method: 'POST',
      dataType: 'script',
      data: {ip_address: $('#ip_address').val()},
      complete: updateScreenshot
    });
  });
  $('#trigger_click').on('click', function(){
    $.ajax('/remote_control/trigger_click', {
      method: 'POST',
      dataType: 'script',
      data: {ip_address: $('#ip_address').val(), click_x: $('#click_x').val(), click_y: $('#click_y').val()},
      complete: updateScreenshot
    });
  });
  $('#trigger_button').on('click', function(){
    $.ajax('/remote_control/trigger_button', {
      method: 'POST',
      dataType: 'script',
      data: {ip_address: $('#ip_address').val(), button: $('#button').val()},
      complete: updateScreenshot
    });
  });
  $('#launch_app').on('click', function(){
    $.ajax('/remote_control/launch_app', {
      method: 'POST',
      dataType: 'script',
      data: {ip_address: $('#ip_address').val(), app_name: $('#app_name').val()},
      complete: updateScreenshot
    });
  });
  $('#watch_channel').on('click', function(){
    $.ajax('/remote_control/watch_channel', {
      method: 'POST',
      dataType: 'script',
      data: {ip_address: $('#ip_address').val(), channel: $('#channel').val(), watching: $('#watching:checked').length},
      complete: updateScreenshot
    });
  });
  function updateScreenshot(data){
    $('#screenshot_container').html('<img width="100%" src="/screenshot'+data.responseText+'.png"/>');
  }
</script>